# Generated by Django 6.0.4 on 2026-08-04 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0010_shopmembership_pos_pin_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='trialing', max_length=16)),
                ('billing_period', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-yearly'), ('yearly', 'Yearly')], max_length=16)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=32, unique=True)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-yearly'), ('yearly', 'Yearly')], max_length=16)),
                ('amount_paise', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=16)),
                ('provider', models.CharField(default='razorpay', max_length=32)),
                ('provider_order_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('provider_payment_link_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('payment_url', models.URLField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.subscription')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
