# Generated by Django 6.0.4 on 2026-07-15 03:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_buyer_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12),
        ),
    ]
