# Generated by Django 6.0.4 on 2026-08-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_saleitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
