# Generated by Django 6.0.4 on 2026-07-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_gst_rate_inventoryitem_hsn_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystockledger',
            name='quantity_delta',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
