# Generated by Django 6.0.4 on 2026-07-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorystockledger_quantity_delta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystockledger',
            name='event_type',
            field=models.CharField(choices=[('opening_balance', 'Opening balance'), ('adjustment', 'Adjustment'), ('sale', 'Sale'), ('return', 'Return'), ('purchase', 'Purchase'), ('import', 'Import'), ('sync', 'Sync')], max_length=32),
        ),
    ]
