# Generated by Django 6.0.4 on 2026-08-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventorystockledger_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='image_data',
            field=models.TextField(blank=True),
        ),
    ]
