# Generated by Django 6.0.4 on 2026-08-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryitem_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
