# Generated by Django 6.0.4 on 2026-08-07 06:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryitem_reorder_level_inventoryitem_unit'),
        ('shops', '0010_shopmembership_pos_pin_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystockledger',
            name='event_type',
            field=models.CharField(choices=[('opening_balance', 'Opening balance'), ('adjustment', 'Adjustment'), ('sale', 'Sale'), ('return', 'Return'), ('purchase', 'Purchase'), ('import', 'Import'), ('sync', 'Sync'), ('transfer_out', 'Transfer out'), ('transfer_in', 'Transfer in')], max_length=32),
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('source_path', models.CharField(blank=True, max_length=255)),
                ('migrated_at', models.DateTimeField(blank=True, null=True)),
                ('domain_epoch', models.PositiveIntegerField(default=1)),
                ('reference', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('in_transit', 'In transit'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='in_transit', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('dispatched_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('destination_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='shops.shop')),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_dispatched', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_received', to=settings.AUTH_USER_MODEL)),
                ('source_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to='shops.shop')),
            ],
            options={
                'ordering': ['-dispatched_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('source_shop_id', models.CharField(blank=True, max_length=128)),
                ('source_path', models.CharField(blank=True, max_length=255)),
                ('migrated_at', models.DateTimeField(blank=True, null=True)),
                ('domain_epoch', models.PositiveIntegerField(default=1)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('destination_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_lines_in', to='inventory.inventoryitem')),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines_out', to='inventory.inventoryitem')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktransfer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['source_shop', 'status'], name='inventory_s_source__80a8e5_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['destination_shop', 'status'], name='inventory_s_destina_19e548_idx'),
        ),
    ]
