# Generated by Django 6.0.4 on 2026-07-07 18:14

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(blank=True, max_length=254)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='-', max_length=32)),
        ),
    ]
