# Generated by Django 6.0.4 on 2026-07-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_email_alter_customer_phone'),
        ('shops', '0006_shop_gstin_shop_region_code_shop_state_code'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_c_shop_id_2daa30_idx',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['shop', 'phone_hash'], name='customers_c_shop_id_446905_idx'),
        ),
    ]
