# Generated by Django 6.0.4 on 2026-08-04 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_backfill_phone_hash'),
        ('shops', '0010_shopmembership_pos_pin_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LoyaltyLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('source_shop_id', models.CharField(blank=True, max_length=128)),
                ('source_path', models.CharField(blank=True, max_length=255)),
                ('migrated_at', models.DateTimeField(blank=True, null=True)),
                ('domain_epoch', models.PositiveIntegerField(default=1)),
                ('event_type', models.CharField(choices=[('earned', 'Earned'), ('redeemed', 'Redeemed'), ('adjustment', 'Adjustment'), ('expired', 'Expired')], max_length=16)),
                ('points_delta', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=280)),
                ('sale_id', models.UUIDField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_entries', to='customers.customer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_entries', to='shops.shop')),
            ],
            options={
                'ordering': ('-occurred_at', '-created_at'),
                'indexes': [models.Index(fields=['shop', 'customer'], name='customers_l_shop_id_360223_idx')],
            },
        ),
    ]
