# Generated by Django 6.0.4 on 2026-08-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_loyalty_points_loyaltyledgerentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
