# Generated by Django 6.0.4 on 2026-07-24 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_shop_gstin_shop_region_code_shop_state_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('accountant', 'Accountant'), ('hr', 'HR'), ('cashier', 'Cashier'), ('sales_staff', 'Sales Staff'), ('inventory_staff', 'Inventory Staff'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='staff', max_length=16),
        ),
        migrations.CreateModel(
            name='ShopInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('source_shop_id', models.CharField(blank=True, max_length=128)),
                ('source_path', models.CharField(blank=True, max_length=255)),
                ('migrated_at', models.DateTimeField(blank=True, null=True)),
                ('domain_epoch', models.PositiveIntegerField(default=1)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('accountant', 'Accountant'), ('hr', 'HR'), ('cashier', 'Cashier'), ('sales_staff', 'Sales Staff'), ('inventory_staff', 'Inventory Staff'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='staff', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('message', models.CharField(blank=True, max_length=280)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='shops.shop')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'status'], name='shops_shopi_shop_id_666ed2_idx'), models.Index(fields=['email'], name='shops_shopi_email_9d9f4a_idx')],
            },
        ),
    ]
