# Generated by Django 6.0.4 on 2026-07-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_alter_shopmembership_role_shopinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceaccesssession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspaceaccesssession',
            name='user_agent',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
