# Generated by Django 6.0.4 on 2026-07-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_workspaceaccesssession_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='shop',
            name='status_reason',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
