# Generated by Django 6.0.4 on 2026-07-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_shop_status_and_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmembership',
            name='pos_pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
