# Generated by Django 6.0.4 on 2026-07-28 06:08

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_shopmembership_pos_pin_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmembership',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(blank=True, max_length=254)),
        ),
        migrations.AlterField(
            model_name='shopmembership',
            name='phone',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=32)),
        ),
    ]
